server:
  port: 10010 #网关端口
spring:
  application:
    name: gateway
  datasource:
        username: root
        password: whj131420
        url: jdbc:mysql://localhost:3306/whhdb
        driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
        server-addr: http://localhost:8848 # nacos服务地址
    gateway:
      routes:
        - id: user_service  #路由id
          uri: lb://userservice #目标地址
          predicates: #路由断言 判断请求是否符合条件
              - Path=/whh/user/** #判断是否是/whh/user开头的
        - id: order_service  #路由id
          uri: lb://orderservice #目标地址
          predicates: #路由断言 判断请求是否符合条件
              - Path=/whh/order/** #判断是否是/whh/user开头的
          filters:
             - AddRequestHeader=token,admin
      default-filters:
        - AddRequestHeader=origin,gateway
#跨域问题----------------------------------------------------------------
#      globalcors:
#        add-to-simple-url-handler-mapping: true #解决options  请求拦截问题
#        cors-configurations:
#           '[/**]':
#              allowedOrigins: #允许那些网站跨域请求
#                - "http://localhost:8090"
#              allowedMethods:
#                - "GET"
#                - "POST"
#                - "DELETE"
#                - "PUT"
#                - "OPTIONS"
#              allowedHeaders: "*" #允许请求头中携带的头信息
#              allowCredentials: true #是否携带cookie
#              maxAge: 360000 #跨域检测的有效期