server:
  port: 6666
spring:
  cache:
    type: redis
  redis:
    port: 6379
    host: localhost
  datasource:
      username: root
      password: whj131420
      url: jdbc:mysql://localhost:3306/whhdb
      driver-class-name: com.mysql.cj.jdbc.Driver